##docker-compose.yml
version: "2"
services:
  app:
    container_name: ive
    build: .
    env_file: .env
    depends_on:
      - neo4j
    ports:            ## publish ports
      - "5000:5000"
    links:            ## connects neo4j to app container
      - neo4j
    volumes:
      - ./public/images:/usr/src/app/public/images
      - ./public/objects:/usr/src/app/public/objects
      - ./public/thumbnails:/usr/src/app/public/thumbails
      - ./public/videos:/usr/src/app/public/videos

  neo4j:
    container_name: neo4j
    image: neo4j:3.0          ## we use neo4j v3
    env_file: .env
    ports:                    ## publish ports to have Web UI
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data:/data
